name: Node.js CI

on:
  push:
    branches:
      - dev  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the appropriate operating system

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'Project'  # Adjust if your repository content is nested

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as per your project requirements

      - name: Install dependencies
        run: npm install
        working-directory: Project

      - name: Deploy to EC2 (example)
        if: github.ref == 'refs/heads/main'  # Adjust branch name if necessary
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu
          DEST_PATH: ~/demo
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r ./Project $EC2_USER@$EC2_HOST:$DEST_PATH
          rm key.pem
