name: Deploy to EC2

on:
  push:
    branches:
      - dev  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'Project'  # Adjust if your repository content is nested

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu
          DEST_PATH: ~/demo  # Adjust destination path on EC2 as needed
        run: |
          scp -i ~/.ssh/id_rsa -r ./Project/* $EC2_USER@$EC2_HOST:$DEST_PATH
          if [ $? -eq 0 ]; then
            echo "Files copied successfully."
          else
            echo "Failed to copy files to EC2."
            exit 1
          fi
